BoxLayout:
    orientation: 'vertical'
#    orientation: 'horizontal'
    Button:
        text: 'Clear'
    Button:
        text: 'Guido'
            TextInput:
            id: input_name
            self.root.ids.output_label.text:f"Hello{self.root,ids,input_name.text}"
    Button:
        text: 'Greet'
        on_press:app.handle_greet()
        id:output_label
    Label:
        text:"Zar Chi Oo"
        color:(1,1,0,1)

